# Generated by Django 2.1 on 2023-06-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.TextField()),
                ('artist', models.TextField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
